name: Build and deploy to GH Pages

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Deploy to gh pages
      run: |
        npx angular-cli-ghpages --dir=dist/taras
      env:
        CI: true
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
